# Generated by Django 5.1.4 on 2025-02-16 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('especie', models.CharField(max_length=50)),
                ('raza', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(max_length=50)),
                ('tamaño', models.CharField(choices=[('Pequeño', 'Pequeño'), ('Mediano', 'Mediano'), ('Grande', 'Grande')], max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Perdido', 'Perdido'), ('Adoptado', 'Adoptado'), ('Disponible', 'Disponible')], max_length=50)),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='mascotas/')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tablaPrueva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField(null=True)),
                ('imajen', models.ImageField(null=True, upload_to='imagenes/')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=128)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tablaVinculada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tablaPrueva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginaWeb.tablaprueva')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginaWeb.mascota')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginaWeb.usuario')),
            ],
        ),
    ]
