# Generated by Django 5.1.6 on 2025-02-27 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginaWeb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablavinculada',
            name='tablaPrueva',
        ),
        migrations.DeleteModel(
            name='tablaPrueva',
        ),
        migrations.DeleteModel(
            name='tablaVinculada',
        ),
    ]
