# Generated by Django 5.1.6 on 2025-03-01 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginaWeb', '0003_alter_mascota_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='color',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='descripcion',
            field=models.TextField(default='Sin descripcion'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='especie',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='estado',
            field=models.CharField(default='Perdido', max_length=10),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='latitud',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='longitud',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(default='Sin raza', max_length=100),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tamaño',
            field=models.CharField(max_length=100),
        ),
    ]
