# Generated by Django 5.1.6 on 2025-03-02 15:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginaWeb', '0004_alter_mascota_color_alter_mascota_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
