# Generated by Django 5.1.6 on 2025-03-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginaWeb', '0005_mascota_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='especie',
        ),
        migrations.AddField(
            model_name='mascota',
            name='contacto',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AddField(
            model_name='mascota',
            name='genero',
            field=models.CharField(default='Desconocido', max_length=10),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(max_length=100),
        ),
    ]
