# Generated by Django 5.1.6 on 2025-03-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginaWeb', '0006_remove_mascota_especie_mascota_contacto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='latitud',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='longitud',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
